#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.Canvas.Android.Resource", IsApplication=true)]

namespace Xamarin.Canvas.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cover1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cover10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cover2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cover3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cover4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cover5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cover6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cover7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cover8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cover9 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
